version: "3"

services:
  timetable-postgres:
    image: "postgres:13"
    container_name: timetable-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    logging:
     driver: "json-file"
     options:
       max-size: "100m"

  timetable-redis:
    image: redis:alpine
    container_name: timetable-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    logging:
     driver: "json-file"
     options:
       max-size: "100m"

  timetablebot-python:
    build: ./
    command: alembic upgrade head && python main.py
    container_name: timetablebot-python
    env_file:
      - .env
    depends_on:
      - timetable-postgres
      - timetable-redis
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"