version: "3"

services:
  timetable-postgres:
    image: "postgres:13"
    container_name: timetable-postgres
    env_file:
      - ENV_FILE_PLACEHOLDER
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    logging:
     driver: "json-file"
     options:
       max-size: "100m"

  timetable-redis:
    image: redis:alpine
    container_name: timetable-redis
    env_file:
      - ENV_FILE_PLACEHOLDER
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    logging:
     driver: "json-file"
     options:
       max-size: "100m"