services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=2VZD2z905tdwa_T
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=1_xyTE39A9Rtapv
      - MYSQL_PASSWORD=foqizEiW5wiv_j2
    ports:
      - "3306:3306"
    networks:
      - timetable-network

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - "3000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=1_xyTE39A9Rtapv
      - WORDPRESS_DB_PASSWORD=foqizEiW5wiv_j2
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - timetable-network

volumes:
  db_data:
  wp_data:

networks:
  wordpress-network:
    external: true
